### PR TITLE
Update moderation.py

### PR DESCRIPTION
**Pull request by imshvishal**
Removed mentions as it wad trying to mention Kocked or banned user which in place was invalid-user.

### CODE REVIEW

**Review by DuckMasterAl — CHANGES_REQUESTED** [review]
The "invalid-user" message is a known bug with allowed mentions on Discord. While this can be resolved by just not mentioning the user, it will probably not be changed, and we'll have to wait for Discord to fix the issue on their end.

**Comment by imshvishal** [comment]
Hmm True.

**Comment by TheMoksej** [comment]
> The "invalid-user" message is a known bug with allowed mentions on Discord. While this can be resolved by just not mentioning the user, it will probably not be changed, and we'll have to wait for Discord to fix the issue on their end.

correct, it also seems to be an issue only on mobile

**Comment by imshvishal** [comment]
And what if the banned user and me don't have any other mutual server then it will show invalid-user on pc too.

**Pull request closed without merging**
